import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackButtonHandler from './BackButtonHandler';
import Script from "next/script";
import ClientLayout from "@/app/language-settings/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const csp = [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://accounts.google.com https://www.gstatic.com",
    "connect-src 'self' https://classroom.googleapis.com https://accounts.google.com https://oauth2.googleapis.com https://content-classroom.googleapis.com",
    "frame-src 'self' https://accounts.google.com https://content-classroom.googleapis.com",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: https:",
    "font-src 'self' data:",
  ].join('; ');
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Security-Policy" content={csp} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientLayout>
          <BackButtonHandler />
          {children}
          <Script src="https://apis.google.com/js/api.js" strategy="beforeInteractive" />
        </ClientLayout>
      </body>
    </html>
  );
}
